pipeline {
    agent any
    environment {
        // Define environment variables here
        VERCEL_TOKEN=credentials('vercel_token')
    }
    stages {
        stage('Install Dependencies of App') {
            steps {
                bat 'npm install'
            }
        }
        stage('Build created .... '){
            steps {
                bat 'npm run build'
            }
        }
        stage('Test the App'){
            steps {
                bat 'npm test'
            }
        }
        stage('Deploy on vercel for remote server') {
            steps {
                bat 'vercel --prod --token=%VERCEL_TOKEN%'
            }
        }
    }
}